name: Package Chrome Extension

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(jq -r '.version' manifest.json)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Extension version: $VERSION"
    
    - name: Create extension package
      run: |
        # Create a clean directory for packaging
        mkdir -p dist
        
        # Copy only the necessary extension files
        cp manifest.json dist/
        cp content_script.js dist/
        cp styles.css dist/
        cp background.js dist/
        cp README.md dist/
        
        # Create the zip package
        cd dist
        zip -r "../hnav-extension-v${{ steps.version.outputs.version }}.zip" .
        cd ..
        
        # Also create a generic "latest" version
        cp "hnav-extension-v${{ steps.version.outputs.version }}.zip" "hnav-extension-latest.zip"
    
    - name: Verify package contents
      run: |
        echo "Package contents:"
        unzip -l "hnav-extension-v${{ steps.version.outputs.version }}.zip"
        
        echo "Package size:"
        ls -lh hnav-extension-*.zip
    
    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension-v${{ steps.version.outputs.version }}
        path: |
          hnav-extension-v${{ steps.version.outputs.version }}.zip
          hnav-extension-latest.zip
        retention-days: 90
    
    - name: Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          hnav-extension-v${{ steps.version.outputs.version }}.zip
          hnav-extension-latest.zip
        body: |
          ## HackerNews Navigator Extension v${{ steps.version.outputs.version }}
          
          ### Installation Instructions
          1. Download the `hnav-extension-v${{ steps.version.outputs.version }}.zip` file
          2. Extract the zip file to a folder
          3. Open Chrome and go to `chrome://extensions/`
          4. Enable "Developer mode" in the top right
          5. Click "Load unpacked" and select the extracted folder
          
          ### Features
          - Keyboard navigation with j/k and arrow keys
          - Save stories with Shift+S
          - In-page modal for saved entries (Cmd/Ctrl+K)
          - Light theme modal interface
          - Smart page handling across HN navigation
          
          ### Keyboard Shortcuts
          - `↑`/`↓` or `j`/`k`: Navigate stories
          - `Enter` or `o`: Open story
          - `Shift+Enter` or `Shift+O`: Open story in new tab
          - `Shift+S`: Save story for later
          - `Cmd/Ctrl+K`: Open saved entries modal
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
